// Glossary for Context Compass - one-liner explanations of each selectable option

export const glossary = {
  // Industries
  "Industrial Manufacturing": "Production of goods using machinery, labor, and assembly lines — covers discrete and process manufacturing.",
  "Automotive": "Vehicle design, production, and supply chain — OEMs, tier suppliers, and aftermarket.",
  "Consumer Products": "Branded goods sold to end consumers — FMCG, durables, and lifestyle products.",
  "Life Sciences": "Pharmaceuticals, biotech, and medical devices — heavily regulated, R&D intensive.",
  "Chemicals": "Production and distribution of chemical compounds — specialty, commodity, and agrochemicals.",
  "Aerospace & Defense": "Aircraft, space systems, and defense equipment — long lifecycles, strict compliance.",
  "High Tech": "Electronics, semiconductors, and technology hardware — fast innovation cycles.",
  "Oil & Gas": "Upstream exploration, midstream transport, and downstream refining of petroleum.",
  "Mining": "Extraction of minerals and metals — capital intensive, remote operations.",
  "Utilities": "Generation and distribution of electricity, water, and gas to consumers.",
  "Retail": "Selling goods directly to consumers — omnichannel, e-commerce, and brick-and-mortar.",
  "Wholesale Distribution": "Bulk purchasing and reselling to retailers or businesses — logistics heavy.",
  "Professional Services": "Knowledge-based services — consulting, legal, accounting, and IT services.",
  "Public Sector": "Government agencies and public institutions — procurement, compliance, citizen services.",
  "Banking": "Financial services — retail banking, commercial lending, risk management.",
  "Insurance": "Risk underwriting, policy management, claims processing.",
  "Healthcare": "Hospitals, clinics, and health systems — patient care, billing, compliance.",
  "Telecommunications": "Network operators and service providers — subscriber management, infrastructure.",
  "Media & Entertainment": "Content creation, distribution, and monetization — streaming, publishing, gaming.",
  "Transportation & Logistics": "Moving goods and people — freight, shipping, fleet management.",
  "Pharmaceuticals": "Drug development, manufacturing, and distribution — regulatory compliance, clinical trials.",
  "Logistics": "Supply chain coordination and freight management — warehousing, distribution, last-mile delivery.",
  "Transportation": "Moving people and goods via land, sea, or air — fleet operations, route optimization.",
  "Media": "Content creation and distribution — broadcasting, publishing, digital platforms.",
  
  // Process Domains  
  "Lead to Cash": "End-to-end revenue cycle — from marketing lead through sales opportunity to invoice collection.",
  "Source to Pay": "Procurement lifecycle — supplier selection, purchasing, receiving, and payment.",
  "Procure to Pay": "Procurement lifecycle — supplier selection, purchasing, receiving, and payment.",
  "Design to Operate": "Product lifecycle — from R&D design through manufacturing to ongoing operations.",
  "Record to Report": "Financial close process — journal entries, consolidation, and financial reporting.",
  "Order to Cash": "Order fulfillment cycle — order capture, delivery, invoicing, and cash collection.",
  "Plan to Fulfill": "Supply chain planning through production execution and delivery.",
  "Hire to Retire": "Employee lifecycle — recruiting, onboarding, development, payroll, and offboarding.",
  "Request to Service": "Service delivery — from customer request through resolution and feedback.",
  "Idea to Market": "Innovation pipeline — ideation, development, launch, and market feedback.",
  "Asset Management": "Tracking and maintaining physical assets — maintenance, depreciation, lifecycle.",
  "Acquire to Retire": "Asset lifecycle management — procurement, deployment, maintenance, and disposal of physical assets.",
  "Campaign to Lead": "Marketing execution — campaign planning, execution, lead generation, and nurturing.",
  "Claims to Resolution": "Insurance claims processing — intake, assessment, approval, and payment.",
  "Forecast to Fulfill": "Demand planning through inventory optimization and order fulfillment.",
  "Incident to Resolution": "IT service management — incident logging, triage, resolution, and closure.",
  "Meter to Cash": "Utility billing cycle — meter reading, usage calculation, billing, and payment collection.",
  "Plan to Produce": "Production planning and execution — scheduling, manufacturing, and quality control.",
  "Quote to Cash": "Sales cycle — quote generation, negotiation, order, fulfillment, and payment.",
  "Service to Cash": "Service delivery and monetization — service request, execution, billing, and collection.",
  
  // Value Drivers
  "Cost Reduction": "Lowering operational expenses through automation, consolidation, or process optimization.",
  "Revenue Growth": "Increasing top-line income through new channels, markets, or pricing strategies.",
  "Process Efficiency": "Doing more with less — reducing cycle times, handoffs, and manual steps.",
  "Digital Transformation": "Modernizing operations with cloud, AI, IoT, and data-driven decision making.",
  "Customer Experience": "Improving how customers interact with your brand across all touchpoints.",
  "Risk & Compliance": "Meeting regulatory requirements and reducing operational/financial risk.",
  "Sustainability": "Environmental and social responsibility — carbon tracking, circular economy, ESG reporting.",
  "Innovation": "Enabling new business models, products, or services through technology.",
  "Operational Resilience": "Building supply chain and business continuity against disruptions.",
  "Data-Driven Decisions": "Using analytics, AI, and real-time data to inform strategy and operations.",
  "Reduce Days Sales Outstanding": "Accelerating cash collection by shortening the time between sale and payment.",
  "Improve Net Working Capital": "Optimizing the balance between current assets and liabilities for better liquidity.",
  "Reduce Total Logistics Cost": "Lowering transportation, warehousing, and distribution expenses.",
  "Reduce Finance Cost": "Cutting costs in financial operations through automation and process improvement.",
  "Reduce Sales Cost": "Improving sales productivity and reducing cost per acquisition.",
  "Reduce Manufacturing Cost": "Optimizing production efficiency and reducing waste in manufacturing.",
  "Reduce Asset Maintenance Cost": "Lowering costs through predictive maintenance and asset optimization.",
  "Reduce Unplanned Downtime": "Minimizing production interruptions through proactive maintenance.",
  "Reduce Waste Generation Cost": "Cutting waste disposal costs and improving sustainability.",
  "Reduce Service & Support Cost": "Improving first-time-fix rates and reducing support overhead.",
  "Improve Procurement FTE Productivity": "Enabling procurement teams to do more with less through automation.",
  "Reduce Uncollectible Accounts Receivable": "Minimizing bad debt through better credit management.",
  "Improve On-Time Delivery": "Meeting customer delivery commitments more consistently.",
  "Improve Customer Satisfaction": "Enhancing customer experience across all touchpoints.",
  "Increase Forecast Accuracy": "Improving demand planning precision to reduce inventory and stockouts.",
  "Improve Compliance": "Meeting regulatory requirements and reducing audit risk.",
  "Increase First-Time-Right": "Reducing rework by getting things right the first time.",
  "Reduce Cycle Time": "Shortening end-to-end process duration for faster outcomes.",
  "Increase Automation Rate": "Reducing manual work through intelligent automation.",
  
  // Capabilities
  "SAP S/4HANA": "Intelligent ERP suite — real-time analytics, simplified data model, in-memory computing.",
  "SAP BTP": "Business Technology Platform — integration, extension, AI, and data management layer.",
  "Signavio": "Business process intelligence — process mining, modeling, and continuous improvement.",
  "SAP Signavio": "Business process intelligence — process mining, modeling, and continuous improvement.",
  "SAP Signavio - all": "Complete business process intelligence suite — mining, modeling, journey mapping, and automation.",
  "LeanIX": "Enterprise architecture management — application rationalization, transformation planning.",
  "SAP LeanIX": "Enterprise architecture management — application rationalization, transformation planning.",
  "SAP LeanIX - all": "Complete enterprise architecture platform — application portfolio, tech stack, and cloud maturity.",
  "WalkMe": "Digital adoption platform — in-app guidance, analytics, and user onboarding.",
  "WalkMe - all": "Complete digital adoption suite — guided workflows, analytics, and change enablement.",
  "SAP SuccessFactors": "Cloud HCM suite — recruiting, learning, performance, payroll, and workforce analytics.",
  "SAP Ariba": "Procurement and supply chain collaboration network — sourcing, contracts, invoicing.",
  "SAP CX": "Customer experience suite — commerce, sales, service, marketing, and CDP.",
  "SAP IBP": "Integrated Business Planning — demand, supply, inventory, and S&OP planning.",
  "SAP Analytics Cloud": "Planning, BI, and predictive analytics in one cloud solution.",
  "SAP Concur": "Travel, expense, and invoice management — automated compliance and reporting.",
  "SAP Fieldglass": "External workforce management — contingent labor, services procurement.",
  "RISE with SAP": "Business transformation as a service — S/4HANA Cloud, BTP, and business network.",
  "GROW with SAP": "Cloud ERP adoption package for midmarket — preconfigured, fast deployment.",
  "Process Modeling": "Visual documentation and design of business processes — BPMN, flow diagrams.",
  "Process Mining": "Data-driven discovery and analysis of actual process execution from system logs.",
  "Journey Modeling": "Customer and employee journey mapping — touchpoints, pain points, and opportunities.",
  "Application Portfolio Mgmt": "Managing the enterprise application landscape — rationalization, lifecycle, TCO.",
  "Tech Risk Mgmt": "Identifying and mitigating technology risks — EOL, security, compliance.",
  "Digital Adoption": "Accelerating user onboarding and software proficiency through in-app guidance.",
  "Guided Workflows": "Step-by-step in-application guidance to improve user productivity.",
};
