// --- UI STRINGS (Multi-language Support) ---
export const UI_STRINGS = {
  EN: {
    subtitle: "Context & Coaching Generator",
    admin: "Admin",
    reset: "Reset",
    coreContext: "Core Context",
    landscape: "Landscape & Architecture",
    landscapeArchitecture: "LANDSCAPE ARCHITECTURE",
    additionalDetails: "Additional Details",
    additionalDetailsUpper: "ADDITIONAL DETAILS",
    riseOpp: "RISE Opportunity?",
    riseOppLabel: "RISE Opportunity:",
    erpSystemLabel: "ERP System:",
    adoptionLabel: "Adoption:",
    adoptionOpp: "Adoption related?",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "Non-SAP ERP",
    otherSap: "Other SAP",
    otherNonSap: "Other Non-SAP",
    contextAttachments: "Context & Attachments",
    attachFile: "Attach File",
    pastePlaceholder: "Paste specific details...",
    consulting: "Consulting Coach...",
    giveIdeas: "Give me ideas",
    industry: "Industry",
    process: "Process Domain",
    value: "Value Driver",
    capability: "Solution Capability",
    dashboard: "Dashboard",
    exportCsv: "Export CSV",
    resetData: "Reset Data",
    noData: "No data yet.",
    configHistory: "Configuration History",
    savedConfig: "Saved Config",
    restore: "Restore",
    noVersions: "No previous versions saved yet.",
    exportConfig: "Export Config",
    importConfig: "Import Config",
    knowledgeBase: "Knowledge Base",
    aiGuardrails: "AI Guardrails & Sources",
    narrativeMethodology: "Narrative & Methodology",
    dropdownLists: "Dropdown Lists",
    importKnowledge: "Import Knowledge",
    uploadPdf: "Upload PDF/Image to train methodology.",
    selectFile: "Select File",
    analyzing: "Analyzing...",
    valueMethodology: "Value Methodology",
    marketingVoice: "Marketing Voice",
    guardrailsLabel: "Guardrails & Priorities",
    editList: "Edit List",
    confirmReset: "Reset All Context?",
    confirmResetMsg: "This will clear all selected inputs. Unsaved data will be lost.",
    confirmClearAnalytics: "Clear Usage Data?",
    confirmClearAnalyticsMsg: "This will delete all analytics history. It cannot be undone.",
    accessGranted: "Access Granted",
    incorrectPass: "Incorrect Password",
    configSaved: "Configuration Saved",
    helpCenter: "Help Center",
    helpStart: "Getting Started",
    helpAdvanced: "Advanced Functions",
    helpVisual: "Visual Mapping",
    helpAdmin: "Admin & Config",
    noAdditionalContext: "No additional context provided.",
    notSpecified: "Not specified",
    none: "None",
    noContextSelected: "No Context Selected",
    selectContextPrompt: "Select industries, processes, and value drivers to build your context map",
    readyToCoach: "Ready to Coach",
    configureInputsPrompt: "Configure inputs on the left & tap \"Give me ideas\"",
    coachThinking: "Coach is thinking...",
    coachThinkingDesc: "Formulating strategy & talking points",
    briefNotGenerated: "Brief Not Generated",
    generateBriefNow: "Generate Brief Now",
    draftingDocument: "Drafting Document...",
    draftingDesc: "Converting coaching notes to formal brief",
    emptyCoachingTitle: "Unlock Strategic Coaching Insights",
    emptyCoachingDesc: "This AI-powered advisor analyzes your context and delivers tailored coaching on deal strategy, value messaging, and competitive positioning.",
    quickStart: "Quick Start:",
    quickStartManuf: "Manufacturing + Procure to Pay",
    quickStartRetail: "Retail + Order to Cash",
    quickStartFinance: "Banking + Record to Report",
    clearHistory: "Clear History",
    tabs: {
      coaching: "Ideation",
      chat: "Refine with Coach",
      brief: "Formal Brief",
      visual: "Visual Map",
      dealScore: "Deal Pulse"
    },
    actions: {
      competitor: "Competitor Intel",
      draftBrief: "Draft Formal Brief",
      email: "Email",
      objections: "Objections",
      video: "30s Video",
      agenda: "Agenda",
      copy: "Copy Content",
      increaseValue: "Increase Value Prop!",
      stakeholders: "Stakeholder Map",
      successStory: "Real Success Stories",
      signavio: "Generate BPMN (Signavio)",
      leanix: "Visual Meta Model (LeanIX)",
      discovery: "Smart Discovery",
      swot: "Strategic SWOT",
      insights: "Strategic Insights"
    },
    meddic: {
      title: "MEDDIC Deal Qualification",
      subtitle: "Enterprise sales framework for qualifying opportunities",
      metrics: "Metrics",
      metricsDesc: "Quantifiable business outcomes (ROI, KPIs, savings targets)",
      economicBuyer: "Economic Buyer",
      economicBuyerDesc: "Person with budget authority",
      decisionCriteria: "Decision Criteria",
      decisionCriteriaDesc: "Technical, business, and political criteria",
      decisionProcess: "Decision Process",
      decisionProcessDesc: "Steps, timeline, approval chain",
      identifyPain: "Identify Pain",
      identifyPainDesc: "Critical business pain driving the initiative",
      champion: "Champion",
      championDesc: "Internal advocate who sells on your behalf",
      analyzeAI: "Analyze with AI",
      analyzing: "Analyzing...",
      ruleBasedScore: "Rule-Based",
      aiAssessment: "AI Assessment",
      signals: "What We Know",
      aiEvidence: "AI Evidence",
      missing: "What's Missing",
      questionToAsk: "Key Question to Ask",
      questionsToAsk: "Questions to Strengthen This",
      noSignals: "No evidence captured yet",
      scoreWeak: "Weak",
      scoreModerate: "Moderate",
      scoreStrong: "Strong",
      overallQualification: "Overall Deal Qualification",
      strongDimensions: "Strong",
      moderateDimensions: "Moderate",
      weakDimensions: "Weak",
      aiAnalysisError: "AI analysis failed. Please try again."
    }
  },
  JA: {
    subtitle: "コンテキスト＆コーチングジェネレーター",
    admin: "管理者",
    reset: "リセット",
    coreContext: "コアコンテキスト",
    landscape: "ランドスケープ＆アーキテクチャ",
    landscapeArchitecture: "ランドスケープアーキテクチャ",
    additionalDetails: "追加詳細",
    additionalDetailsUpper: "追加詳細",
    riseOpp: "RISE機会？",
    riseOppLabel: "RISE機会：",
    erpSystemLabel: "ERPシステム：",
    adoptionLabel: "導入：",
    adoptionOpp: "導入関連？",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "非SAP ERP",
    otherSap: "その他SAP",
    otherNonSap: "その他非SAP",
    contextAttachments: "コンテキスト＆添付ファイル",
    attachFile: "ファイル添付",
    pastePlaceholder: "具体的な詳細を貼り付け...",
    consulting: "コンサルティングコーチ...",
    giveIdeas: "アイデアをください",
    industry: "業界",
    process: "プロセスドメイン",
    value: "バリュードライバー",
    capability: "ソリューション機能",
    dashboard: "ダッシュボード",
    exportCsv: "CSV エクスポート",
    resetData: "データリセット",
    noData: "データなし",
    configHistory: "構成履歴",
    savedConfig: "保存済み構成",
    restore: "復元",
    noVersions: "以前のバージョンなし",
    exportConfig: "構成エクスポート",
    importConfig: "構成インポート",
    knowledgeBase: "ナレッジベース",
    aiGuardrails: "AIガードレール＆ソース",
    narrativeMethodology: "ナラティブ＆メソドロジー",
    dropdownLists: "ドロップダウンリスト",
    importKnowledge: "ナレッジインポート",
    uploadPdf: "PDF/画像をアップロードして方法論をトレーニング",
    selectFile: "ファイル選択",
    analyzing: "分析中...",
    valueMethodology: "バリューメソドロジー",
    marketingVoice: "マーケティングボイス",
    guardrailsLabel: "ガードレール＆優先順位",
    editList: "リスト編集",
    confirmReset: "すべてのコンテキストをリセット？",
    confirmResetMsg: "すべての選択した入力がクリアされます。保存されていないデータは失われます。",
    confirmClearAnalytics: "使用データをクリア？",
    confirmClearAnalyticsMsg: "すべての分析履歴が削除されます。元に戻せません。",
    accessGranted: "アクセス許可",
    incorrectPass: "パスワード誤り",
    configSaved: "構成保存完了",
    helpCenter: "ヘルプセンター",
    helpStart: "開始",
    helpAdvanced: "高度な機能",
    helpVisual: "ビジュアルマッピング",
    helpAdmin: "管理者＆構成",
    noAdditionalContext: "追加コンテキストなし",
    notSpecified: "未指定",
    none: "なし",
    noContextSelected: "コンテキスト未選択",
    selectContextPrompt: "業界、プロセス、バリュードライバーを選択してコンテキストマップを作成",
    readyToCoach: "コーチング準備完了",
    configureInputsPrompt: "左側で入力を設定し、「アイデアをください」をタップ",
    coachThinking: "コーチが考え中...",
    coachThinkingDesc: "戦略とトーキングポイントを策定中",
    briefNotGenerated: "ブリーフ未生成",
    generateBriefNow: "今すぐブリーフを生成",
    draftingDocument: "ドキュメント作成中...",
    draftingDesc: "コーチングノートを正式ブリーフに変換中",
    emptyCoachingTitle: "戦略的コーチングインサイトを解放",
    emptyCoachingDesc: "このAI搭載アドバイザーは、コンテキストを分析し、取引戦略、価値メッセージング、競合ポジショニングに関するカスタマイズされたコーチングを提供します。",
    quickStart: "クイックスタート：",
    quickStartManuf: "製造 + 調達から支払い",
    quickStartRetail: "小売 + 受注から現金化",
    quickStartFinance: "銀行 + 記録から報告",
    clearHistory: "履歴をクリア",
    tabs: {
      coaching: "コーチングアイデア",
      chat: "コーチに質問",
      brief: "正式ブリーフ",
      visual: "ビジュアルマップ",
      dealScore: "案件スコア"
    },
    actions: {
      competitor: "競合情報",
      draftBrief: "正式ブリーフドラフト",
      email: "メール",
      objections: "異議",
      video: "30秒ビデオ",
      agenda: "アジェンダ",
      copy: "コンテンツをコピー",
      increaseValue: "価値提案を増やす！",
      stakeholders: "ステークホルダーマップ",
      successStory: "実際の成功事例",
      signavio: "BPMN生成（Signavio）",
      leanix: "ビジュアルメタモデル（LeanIX）",
      discovery: "スマートディスカバリー",
      swot: "戦略的SWOT",
      insights: "戦略的インサイト"
    },
    meddic: {
      title: "MEDDIC案件評価",
      subtitle: "エンタープライズセールス機会評価フレームワーク",
      metrics: "メトリクス",
      metricsDesc: "定量化可能なビジネス成果（ROI、KPI、削減目標）",
      economicBuyer: "経済的購買者",
      economicBuyerDesc: "予算権限を持つ人物",
      decisionCriteria: "決定基準",
      decisionCriteriaDesc: "技術的、ビジネス的、政治的基準",
      decisionProcess: "決定プロセス",
      decisionProcessDesc: "ステップ、タイムライン、承認チェーン",
      identifyPain: "課題特定",
      identifyPainDesc: "イニシアチブを推進する重要なビジネス課題",
      champion: "チャンピオン",
      championDesc: "あなたの代わりに社内で販売する支持者",
      analyzeAI: "AIで分析",
      analyzing: "分析中...",
      ruleBasedScore: "ルールベース",
      aiAssessment: "AI評価",
      signals: "把握していること",
      aiEvidence: "AIエビデンス",
      missing: "不足していること",
      questionToAsk: "質問すべき重要事項",
      questionsToAsk: "これを強化するための質問",
      noSignals: "まだエビデンスが収集されていません",
      scoreWeak: "弱い",
      scoreModerate: "中程度",
      scoreStrong: "強い",
      overallQualification: "総合案件評価",
      strongDimensions: "強い",
      moderateDimensions: "中程度",
      weakDimensions: "弱い",
      aiAnalysisError: "AI分析に失敗しました。もう一度お試しください。"
    }
  },
  TH: {
    subtitle: "ตัวสร้างบริบทและโค้ช",
    admin: "ผู้ดูแลระบบ",
    reset: "รีเซ็ต",
    coreContext: "บริบทหลัก",
    landscape: "ภูมิทัศน์และสถาปัตยกรรม",
    landscapeArchitecture: "สถาปัตยกรรมภูมิทัศน์",
    additionalDetails: "รายละเอียดเพิ่มเติม",
    additionalDetailsUpper: "รายละเอียดเพิ่มเติม",
    riseOpp: "โอกาส RISE?",
    riseOppLabel: "โอกาส RISE:",
    erpSystemLabel: "ระบบ ERP:",
    adoptionLabel: "การนำไปใช้:",
    adoptionOpp: "เกี่ยวข้องกับการนำไปใช้?",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "ERP ที่ไม่ใช่ SAP",
    otherSap: "SAP อื่นๆ",
    otherNonSap: "ที่ไม่ใช่ SAP อื่นๆ",
    contextAttachments: "บริบทและไฟล์แนบ",
    attachFile: "แนบไฟล์",
    pastePlaceholder: "วางรายละเอียดเฉพาะ...",
    consulting: "กำลังให้คำปรึกษา...",
    giveIdeas: "ให้ไอเดีย",
    industry: "อุตสาหกรรม",
    process: "โดเมนกระบวนการ",
    value: "ตัวขับเคลื่อนคุณค่า",
    capability: "ความสามารถของโซลูชัน",
    dashboard: "แดชบอร์ด",
    exportCsv: "ส่งออก CSV",
    resetData: "รีเซ็ตข้อมูล",
    noData: "ยังไม่มีข้อมูล",
    configHistory: "ประวัติการกำหนดค่า",
    savedConfig: "การกำหนดค่าที่บันทึก",
    restore: "กู้คืน",
    noVersions: "ยังไม่มีเวอร์ชันก่อนหน้า",
    exportConfig: "ส่งออกการกำหนดค่า",
    importConfig: "นำเข้าการกำหนดค่า",
    knowledgeBase: "ฐานความรู้",
    aiGuardrails: "กรอบความปลอดภัย AI และแหล่งที่มา",
    narrativeMethodology: "การเล่าเรื่องและวิธีการ",
    dropdownLists: "รายการแบบเลื่อนลง",
    importKnowledge: "นำเข้าความรู้",
    uploadPdf: "อัปโหลด PDF/รูปภาพเพื่อฝึกวิธีการ",
    selectFile: "เลือกไฟล์",
    analyzing: "กำลังวิเคราะห์...",
    valueMethodology: "วิธีการคุณค่า",
    marketingVoice: "เสียงการตลาด",
    guardrailsLabel: "กรอบความปลอดภัยและลำดับความสำคัญ",
    editList: "แก้ไขรายการ",
    confirmReset: "รีเซ็ตบริบททั้งหมด?",
    confirmResetMsg: "จะล้างข้อมูลที่เลือกทั้งหมด ข้อมูลที่ไม่ได้บันทึกจะหายไป",
    confirmClearAnalytics: "ล้างข้อมูลการใช้งาน?",
    confirmClearAnalyticsMsg: "จะลบประวัติการวิเคราะห์ทั้งหมด ไม่สามารถยกเลิกได้",
    accessGranted: "อนุญาตการเข้าถึง",
    incorrectPass: "รหัสผ่านไม่ถูกต้อง",
    configSaved: "บันทึกการกำหนดค่าแล้ว",
    helpCenter: "ศูนย์ช่วยเหลือ",
    helpStart: "เริ่มต้นใช้งาน",
    helpAdvanced: "ฟังก์ชันขั้นสูง",
    helpVisual: "การแมปภาพ",
    helpAdmin: "ผู้ดูแลและการกำหนดค่า",
    noAdditionalContext: "ไม่มีบริบทเพิ่มเติม",
    notSpecified: "ไม่ได้ระบุ",
    none: "ไม่มี",
    noContextSelected: "ไม่ได้เลือกบริบท",
    selectContextPrompt: "เลือกอุตสาหกรรม กระบวนการ และตัวขับเคลื่อนคุณค่าเพื่อสร้างแผนที่บริบท",
    readyToCoach: "พร้อมให้คำปรึกษา",
    configureInputsPrompt: "กำหนดค่าด้านซ้ายและแตะ \"ให้ไอเดีย\"",
    coachThinking: "โค้ชกำลังคิด...",
    coachThinkingDesc: "กำลังกำหนดกลยุทธ์และประเด็นสนทนา",
    briefNotGenerated: "ยังไม่ได้สร้างสรุป",
    generateBriefNow: "สร้างสรุปทันที",
    draftingDocument: "กำลังร่างเอกสาร...",
    draftingDesc: "กำลังแปลงบันทึกโค้ชเป็นสรุปอย่างเป็นทางการ",
    emptyCoachingTitle: "ปลดล็อกข้อมูลเชิงลึกเชิงกลยุทธ์",
    emptyCoachingDesc: "ที่ปรึกษา AI นี้วิเคราะห์บริบทของคุณและให้คำปรึกษาแบบกำหนดเองเกี่ยวกับกลยุทธ์ข้อตกลง การส่งสารคุณค่า และการวางตำแหน่งการแข่งขัน",
    quickStart: "เริ่มต้นด่วน:",
    quickStartManuf: "การผลิต + จัดซื้อถึงจ่าย",
    quickStartRetail: "ค้าปลีก + คำสั่งซื้อถึงเงินสด",
    quickStartFinance: "ธนาคาร + บันทึกถึงรายงาน",
    clearHistory: "ล้างประวัติ",
    tabs: {
      coaching: "ไอเดียโค้ช",
      chat: "ถามโค้ช",
      brief: "สรุปอย่างเป็นทางการ",
      visual: "แผนที่ภาพ",
      dealScore: "คะแนนดีล"
    },
    actions: {
      competitor: "ข้อมูลคู่แข่ง",
      draftBrief: "ร่างสรุปอย่างเป็นทางการ",
      email: "อีเมล",
      objections: "ข้อโต้แย้ง",
      video: "วิดีโอ 30 วินาที",
      agenda: "วาระ",
      copy: "คัดลอกเนื้อหา",
      increaseValue: "เพิ่มข้อเสนอคุณค่า!",
      stakeholders: "แผนที่ผู้มีส่วนได้ส่วนเสีย",
      successStory: "เรื่องราวความสำเร็จจริง",
      signavio: "สร้าง BPMN (Signavio)",
      leanix: "โมเดลเมตาภาพ (LeanIX)",
      discovery: "การค้นพบอัจฉริยะ",
      swot: "SWOT เชิงกลยุทธ์",
      insights: "ข้อมูลเชิงลึกเชิงกลยุทธ์"
    },
    meddic: {
      title: "MEDDIC การประเมินดีล",
      subtitle: "กรอบการทำงานการขายองค์กรสำหรับการคัดเลือกโอกาส",
      metrics: "เมตริก",
      metricsDesc: "ผลลัพธ์ทางธุรกิจที่วัดได้ (ROI, KPI, เป้าหมายการประหยัด)",
      economicBuyer: "ผู้ซื้อเชิงเศรษฐกิจ",
      economicBuyerDesc: "บุคคลที่มีอำนาจในงบประมาณ",
      decisionCriteria: "เกณฑ์การตัดสินใจ",
      decisionCriteriaDesc: "เกณฑ์ทางเทคนิค ธุรกิจ และการเมือง",
      decisionProcess: "กระบวนการตัดสินใจ",
      decisionProcessDesc: "ขั้นตอน ไทม์ไลน์ ห่วงโซ่การอนุมัติ",
      identifyPain: "ระบุปัญหา",
      identifyPainDesc: "ปัญหาทางธุรกิจที่สำคัญที่ขับเคลื่อนความคิดริเริ่ม",
      champion: "แชมเปี้ยน",
      championDesc: "ผู้สนับสนุนภายในที่ขายในนามของคุณ",
      analyzeAI: "วิเคราะห์ด้วย AI",
      analyzing: "กำลังวิเคราะห์...",
      ruleBasedScore: "คะแนนตามกฎ",
      aiAssessment: "การประเมินของ AI",
      signals: "สิ่งที่เรารู้",
      aiEvidence: "หลักฐาน AI",
      missing: "สิ่งที่ขาดหายไป",
      questionToAsk: "คำถามสำคัญที่ควรถาม",
      questionsToAsk: "คำถามเพื่อเสริมสร้างสิ่งนี้",
      noSignals: "ยังไม่มีหลักฐานที่บันทึกไว้",
      scoreWeak: "อ่อนแอ",
      scoreModerate: "ปานกลาง",
      scoreStrong: "แข็งแกร่ง",
      overallQualification: "การประเมินดีลโดยรวม",
      strongDimensions: "แข็งแกร่ง",
      moderateDimensions: "ปานกลาง",
      weakDimensions: "อ่อนแอ",
      aiAnalysisError: "การวิเคราะห์ AI ล้มเหลว กรุณาลองอีกครั้ง"
    }
  },
  ID: {
    subtitle: "Generator Konteks & Coaching",
    admin: "Admin",
    reset: "Atur Ulang",
    coreContext: "Konteks Inti",
    landscape: "Lanskap & Arsitektur",
    landscapeArchitecture: "ARSITEKTUR LANSKAP",
    additionalDetails: "Detail Tambahan",
    additionalDetailsUpper: "DETAIL TAMBAHAN",
    riseOpp: "Peluang RISE?",
    riseOppLabel: "Peluang RISE:",
    erpSystemLabel: "Sistem ERP:",
    adoptionLabel: "Adopsi:",
    adoptionOpp: "Terkait adopsi?",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "ERP Non-SAP",
    otherSap: "SAP Lainnya",
    otherNonSap: "Non-SAP Lainnya",
    contextAttachments: "Konteks & Lampiran",
    attachFile: "Lampirkan File",
    pastePlaceholder: "Tempel detail spesifik...",
    consulting: "Coaching Konsultan...",
    giveIdeas: "Beri saya ide",
    industry: "Industri",
    process: "Domain Proses",
    value: "Pendorong Nilai",
    capability: "Kemampuan Solusi",
    dashboard: "Dasbor",
    exportCsv: "Ekspor CSV",
    resetData: "Atur Ulang Data",
    noData: "Belum ada data.",
    configHistory: "Riwayat Konfigurasi",
    savedConfig: "Konfigurasi Tersimpan",
    restore: "Pulihkan",
    noVersions: "Belum ada versi sebelumnya yang disimpan.",
    exportConfig: "Ekspor Konfigurasi",
    importConfig: "Impor Konfigurasi",
    knowledgeBase: "Basis Pengetahuan",
    aiGuardrails: "Pedoman AI & Sumber",
    narrativeMethodology: "Narasi & Metodologi",
    dropdownLists: "Daftar Dropdown",
    importKnowledge: "Impor Pengetahuan",
    uploadPdf: "Unggah PDF/Gambar untuk melatih metodologi.",
    selectFile: "Pilih File",
    analyzing: "Menganalisis...",
    valueMethodology: "Metodologi Nilai",
    marketingVoice: "Suara Pemasaran",
    guardrailsLabel: "Pedoman & Prioritas",
    editList: "Edit Daftar",
    confirmReset: "Atur Ulang Semua Konteks?",
    confirmResetMsg: "Ini akan menghapus semua input yang dipilih. Data yang tidak disimpan akan hilang.",
    confirmClearAnalytics: "Hapus Data Penggunaan?",
    confirmClearAnalyticsMsg: "Ini akan menghapus semua riwayat analitik. Tidak dapat dibatalkan.",
    accessGranted: "Akses Diberikan",
    incorrectPass: "Kata Sandi Salah",
    configSaved: "Konfigurasi Disimpan",
    helpCenter: "Pusat Bantuan",
    helpStart: "Memulai",
    helpAdvanced: "Fungsi Lanjutan",
    helpVisual: "Pemetaan Visual",
    helpAdmin: "Admin & Konfigurasi",
    noAdditionalContext: "Tidak ada konteks tambahan yang diberikan.",
    notSpecified: "Tidak ditentukan",
    none: "Tidak ada",
    noContextSelected: "Tidak Ada Konteks yang Dipilih",
    selectContextPrompt: "Pilih industri, proses, dan pendorong nilai untuk membangun peta konteks",
    readyToCoach: "Siap untuk Coaching",
    configureInputsPrompt: "Konfigurasikan input di kiri & ketuk \"Beri saya ide\"",
    coachThinking: "Coach sedang berpikir...",
    coachThinkingDesc: "Merumuskan strategi & poin pembicaraan",
    briefNotGenerated: "Brief Belum Dibuat",
    generateBriefNow: "Buat Brief Sekarang",
    draftingDocument: "Menyusun Dokumen...",
    draftingDesc: "Mengonversi catatan coaching menjadi brief formal",
    emptyCoachingTitle: "Buka Wawasan Coaching Strategis",
    emptyCoachingDesc: "Penasihat bertenaga AI ini menganalisis konteks Anda dan memberikan coaching yang disesuaikan tentang strategi kesepakatan, pesan nilai, dan positioning kompetitif.",
    quickStart: "Mulai Cepat:",
    quickStartManuf: "Manufaktur + Pengadaan hingga Pembayaran",
    quickStartRetail: "Ritel + Pesanan hingga Kas",
    quickStartFinance: "Perbankan + Pencatatan hingga Pelaporan",
    clearHistory: "Hapus Riwayat",
    tabs: {
      coaching: "Ide Coaching",
      chat: "Tanya Coach",
      brief: "Brief Formal",
      visual: "Peta Visual",
      dealScore: "Skor Deal"
    },
    actions: {
      competitor: "Intelijen Pesaing",
      draftBrief: "Draft Brief Formal",
      email: "Email",
      objections: "Keberatan",
      video: "Video 30 detik",
      agenda: "Agenda",
      copy: "Salin Konten",
      increaseValue: "Tingkatkan Proposisi Nilai!",
      stakeholders: "Peta Pemangku Kepentingan",
      successStory: "Kisah Sukses Nyata",
      signavio: "Buat BPMN (Signavio)",
      leanix: "Model Meta Visual (LeanIX)",
      discovery: "Penemuan Cerdas",
      swot: "SWOT Strategis",
      insights: "Wawasan Strategis"
    },
    meddic: {
      title: "Kualifikasi Deal MEDDIC",
      subtitle: "Kerangka penjualan enterprise untuk mengkualifikasi peluang",
      metrics: "Metrik",
      metricsDesc: "Hasil bisnis yang terukur (ROI, KPI, target penghematan)",
      economicBuyer: "Pembeli Ekonomi",
      economicBuyerDesc: "Orang dengan otoritas anggaran",
      decisionCriteria: "Kriteria Keputusan",
      decisionCriteriaDesc: "Kriteria teknis, bisnis, dan politik",
      decisionProcess: "Proses Keputusan",
      decisionProcessDesc: "Langkah, timeline, rantai persetujuan",
      identifyPain: "Identifikasi Masalah",
      identifyPainDesc: "Masalah bisnis kritis yang mendorong inisiatif",
      champion: "Juara",
      championDesc: "Pendukung internal yang menjual atas nama Anda",
      analyzeAI: "Analisis dengan AI",
      analyzing: "Menganalisis...",
      ruleBasedScore: "Berbasis Aturan",
      aiAssessment: "Penilaian AI",
      signals: "Yang Kita Tahu",
      aiEvidence: "Bukti AI",
      missing: "Yang Hilang",
      questionToAsk: "Pertanyaan Kunci untuk Ditanyakan",
      questionsToAsk: "Pertanyaan untuk Memperkuat Ini",
      noSignals: "Belum ada bukti yang ditangkap",
      scoreWeak: "Lemah",
      scoreModerate: "Sedang",
      scoreStrong: "Kuat",
      overallQualification: "Kualifikasi Deal Keseluruhan",
      strongDimensions: "Kuat",
      moderateDimensions: "Sedang",
      weakDimensions: "Lemah",
      aiAnalysisError: "Analisis AI gagal. Silakan coba lagi."
    }
  },
  KO: {
    subtitle: "컨텍스트 및 코칭 생성기",
    admin: "관리자",
    reset: "초기화",
    coreContext: "핵심 컨텍스트",
    landscape: "랜드스케이프 및 아키텍처",
    landscapeArchitecture: "랜드스케이프 아키텍처",
    additionalDetails: "추가 세부정보",
    additionalDetailsUpper: "추가 세부정보",
    riseOpp: "RISE 기회?",
    riseOppLabel: "RISE 기회:",
    erpSystemLabel: "ERP 시스템:",
    adoptionLabel: "도입:",
    adoptionOpp: "도입 관련?",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "비SAP ERP",
    otherSap: "기타 SAP",
    otherNonSap: "기타 비SAP",
    contextAttachments: "컨텍스트 및 첨부파일",
    attachFile: "파일 첨부",
    pastePlaceholder: "구체적인 세부정보 붙여넣기...",
    consulting: "컨설팅 코치...",
    giveIdeas: "아이디어 주세요",
    industry: "산업",
    process: "프로세스 도메인",
    value: "가치 동인",
    capability: "솔루션 역량",
    dashboard: "대시보드",
    exportCsv: "CSV 내보내기",
    resetData: "데이터 초기화",
    noData: "아직 데이터 없음.",
    configHistory: "구성 기록",
    savedConfig: "저장된 구성",
    restore: "복원",
    noVersions: "이전 버전이 아직 저장되지 않음.",
    exportConfig: "구성 내보내기",
    importConfig: "구성 가져오기",
    knowledgeBase: "지식 베이스",
    aiGuardrails: "AI 가드레일 및 소스",
    narrativeMethodology: "내러티브 및 방법론",
    dropdownLists: "드롭다운 목록",
    importKnowledge: "지식 가져오기",
    uploadPdf: "방법론을 훈련하기 위해 PDF/이미지를 업로드합니다.",
    selectFile: "파일 선택",
    analyzing: "분석 중...",
    valueMethodology: "가치 방법론",
    marketingVoice: "마케팅 보이스",
    guardrailsLabel: "가드레일 및 우선순위",
    editList: "목록 편집",
    confirmReset: "모든 컨텍스트를 초기화하시겠습니까?",
    confirmResetMsg: "선택한 모든 입력이 지워집니다. 저장하지 않은 데이터는 손실됩니다.",
    confirmClearAnalytics: "사용 데이터를 삭제하시겠습니까?",
    confirmClearAnalyticsMsg: "모든 분석 기록이 삭제됩니다. 실행 취소할 수 없습니다.",
    accessGranted: "액세스 허용됨",
    incorrectPass: "잘못된 비밀번호",
    configSaved: "구성 저장됨",
    helpCenter: "도움말 센터",
    helpStart: "시작하기",
    helpAdvanced: "고급 기능",
    helpVisual: "비주얼 매핑",
    helpAdmin: "관리자 및 구성",
    noAdditionalContext: "추가 컨텍스트가 제공되지 않았습니다.",
    notSpecified: "지정되지 않음",
    none: "없음",
    noContextSelected: "선택된 컨텍스트 없음",
    selectContextPrompt: "컨텍스트 맵을 작성하려면 산업, 프로세스 및 가치 동인을 선택하세요",
    readyToCoach: "코칭 준비 완료",
    configureInputsPrompt: "왼쪽에서 입력을 구성하고 \"아이디어 주세요\"를 탭하세요",
    coachThinking: "코치가 생각 중...",
    coachThinkingDesc: "전략 및 대화 요점 수립 중",
    briefNotGenerated: "브리프 미생성",
    generateBriefNow: "지금 브리프 생성",
    draftingDocument: "문서 작성 중...",
    draftingDesc: "코칭 노트를 공식 브리프로 변환 중",
    emptyCoachingTitle: "전략적 코칭 인사이트 잠금 해제",
    emptyCoachingDesc: "이 AI 기반 어드바이저는 컨텍스트를 분석하고 거래 전략, 가치 메시징 및 경쟁 포지셔닝에 대한 맞춤형 코칭을 제공합니다.",
    quickStart: "빠른 시작:",
    quickStartManuf: "제조 + 조달에서 지불까지",
    quickStartRetail: "소매 + 주문에서 현금까지",
    quickStartFinance: "은행 + 기록에서 보고까지",
    clearHistory: "기록 지우기",
    tabs: {
      coaching: "코칭 아이디어",
      chat: "코치에게 질문",
      brief: "공식 브리프",
      visual: "비주얼 맵",
      dealScore: "딜 스코어"
    },
    actions: {
      competitor: "경쟁사 인텔",
      draftBrief: "공식 브리프 초안",
      email: "이메일",
      objections: "이의제기",
      video: "30초 비디오",
      agenda: "안건",
      copy: "콘텐츠 복사",
      increaseValue: "가치 제안 증가!",
      stakeholders: "이해관계자 맵",
      successStory: "실제 성공 사례",
      signavio: "BPMN 생성 (Signavio)",
      leanix: "비주얼 메타 모델 (LeanIX)",
      discovery: "스마트 발견",
      swot: "전략적 SWOT",
      insights: "전략적 인사이트"
    },
    meddic: {
      title: "MEDDIC 거래 평가",
      subtitle: "기회를 평가하기 위한 엔터프라이즈 영업 프레임워크",
      metrics: "메트릭",
      metricsDesc: "정량화 가능한 비즈니스 결과 (ROI, KPI, 절감 목표)",
      economicBuyer: "경제적 구매자",
      economicBuyerDesc: "예산 권한이 있는 사람",
      decisionCriteria: "결정 기준",
      decisionCriteriaDesc: "기술적, 비즈니스 및 정치적 기준",
      decisionProcess: "결정 프로세스",
      decisionProcessDesc: "단계, 타임라인, 승인 체인",
      identifyPain: "문제 식별",
      identifyPainDesc: "이니셔티브를 추진하는 중요한 비즈니스 문제",
      champion: "챔피언",
      championDesc: "귀하를 대신하여 판매하는 내부 옹호자",
      analyzeAI: "AI로 분석",
      analyzing: "분석 중...",
      ruleBasedScore: "규칙 기반",
      aiAssessment: "AI 평가",
      signals: "알고 있는 것",
      aiEvidence: "AI 증거",
      missing: "누락된 것",
      questionToAsk: "질문해야 할 핵심 질문",
      questionsToAsk: "이를 강화하기 위한 질문",
      noSignals: "아직 포착된 증거 없음",
      scoreWeak: "약함",
      scoreModerate: "보통",
      scoreStrong: "강함",
      overallQualification: "전체 거래 평가",
      strongDimensions: "강함",
      moderateDimensions: "보통",
      weakDimensions: "약함",
      aiAnalysisError: "AI 분석 실패. 다시 시도하십시오."
    }
  },
  ZH: {
    subtitle: "上下文和指导生成器",
    admin: "管理员",
    reset: "重置",
    coreContext: "核心上下文",
    landscape: "景观和架构",
    landscapeArchitecture: "景观架构",
    additionalDetails: "其他详细信息",
    additionalDetailsUpper: "其他详细信息",
    riseOpp: "RISE 机会？",
    riseOppLabel: "RISE 机会：",
    erpSystemLabel: "ERP 系统：",
    adoptionLabel: "采用：",
    adoptionOpp: "与采用相关？",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "非 SAP ERP",
    otherSap: "其他 SAP",
    otherNonSap: "其他非 SAP",
    contextAttachments: "上下文和附件",
    attachFile: "附加文件",
    pastePlaceholder: "粘贴具体细节...",
    consulting: "咨询顾问中...",
    giveIdeas: "给我想法",
    industry: "行业",
    process: "流程域",
    value: "价值驱动因素",
    capability: "解决方案能力",
    dashboard: "仪表板",
    exportCsv: "导出 CSV",
    resetData: "重置数据",
    noData: "还没有数据。",
    configHistory: "配置历史",
    savedConfig: "已保存的配置",
    restore: "恢复",
    noVersions: "尚未保存以前的版本。",
    exportConfig: "导出配置",
    importConfig: "导入配置",
    knowledgeBase: "知识库",
    aiGuardrails: "AI 护栏和来源",
    narrativeMethodology: "叙事和方法论",
    dropdownLists: "下拉列表",
    importKnowledge: "导入知识",
    uploadPdf: "上传 PDF/图像以训练方法论。",
    selectFile: "选择文件",
    analyzing: "分析中...",
    valueMethodology: "价值方法论",
    marketingVoice: "营销声音",
    guardrailsLabel: "护栏和优先级",
    editList: "编辑列表",
    confirmReset: "重置所有上下文？",
    confirmResetMsg: "这将清除所有选定的输入。未保存的数据将丢失。",
    confirmClearAnalytics: "清除使用数据？",
    confirmClearAnalyticsMsg: "这将删除所有分析历史记录。无法撤消。",
    accessGranted: "已授予访问权限",
    incorrectPass: "密码错误",
    configSaved: "配置已保存",
    helpCenter: "帮助中心",
    helpStart: "入门",
    helpAdvanced: "高级功能",
    helpVisual: "可视化映射",
    helpAdmin: "管理员和配置",
    noAdditionalContext: "未提供其他上下文。",
    notSpecified: "未指定",
    none: "无",
    noContextSelected: "未选择上下文",
    selectContextPrompt: "选择行业、流程和价值驱动因素以构建上下文图",
    readyToCoach: "准备指导",
    configureInputsPrompt: "在左侧配置输入并点击「给我想法」",
    coachThinking: "顾问正在思考...",
    coachThinkingDesc: "制定战略和谈话要点",
    briefNotGenerated: "简报未生成",
    generateBriefNow: "立即生成简报",
    draftingDocument: "起草文档中...",
    draftingDesc: "将指导笔记转换为正式简报",
    emptyCoachingTitle: "解锁战略指导洞察",
    emptyCoachingDesc: "这个由 AI 驱动的顾问分析您的上下文，并提供有关交易策略、价值信息和竞争定位的定制指导。",
    quickStart: "快速启动：",
    quickStartManuf: "制造 + 采购到付款",
    quickStartRetail: "零售 + 订单到现金",
    quickStartFinance: "银行 + 记录到报告",
    clearHistory: "清除历史记录",
    tabs: {
      coaching: "指导想法",
      chat: "询问顾问",
      brief: "正式简报",
      visual: "可视化地图",
      dealScore: "交易评分"
    },
    actions: {
      competitor: "竞争对手情报",
      draftBrief: "起草正式简报",
      email: "电子邮件",
      objections: "反对意见",
      video: "30 秒视频",
      agenda: "议程",
      copy: "复制内容",
      increaseValue: "增加价值主张！",
      stakeholders: "利益相关者地图",
      successStory: "真实成功案例",
      signavio: "生成 BPMN (Signavio)",
      leanix: "可视化元模型 (LeanIX)",
      discovery: "智能发现",
      swot: "战略 SWOT",
      insights: "战略洞察"
    },
    meddic: {
      title: "MEDDIC 交易评估",
      subtitle: "企业销售框架用于评估机会",
      metrics: "指标",
      metricsDesc: "可量化的业务成果 (ROI, KPI, 节省目标)",
      economicBuyer: "经济买家",
      economicBuyerDesc: "拥有预算权限的人",
      decisionCriteria: "决策标准",
      decisionCriteriaDesc: "技术、业务和政治标准",
      decisionProcess: "决策流程",
      decisionProcessDesc: "步骤、时间表、审批链",
      identifyPain: "识别痛点",
      identifyPainDesc: "推动计划的关键业务痛点",
      champion: "支持者",
      championDesc: "代表您销售的内部倡导者",
      analyzeAI: "AI 分析",
      analyzing: "分析中...",
      ruleBasedScore: "基于规则",
      aiAssessment: "AI 评估",
      signals: "我们知道的",
      aiEvidence: "AI 证据",
      missing: "缺失的",
      questionToAsk: "要问的关键问题",
      questionsToAsk: "强化这一点的问题",
      noSignals: "尚未捕获证据",
      scoreWeak: "弱",
      scoreModerate: "中等",
      scoreStrong: "强",
      overallQualification: "整体交易评估",
      strongDimensions: "强",
      moderateDimensions: "中等",
      weakDimensions: "弱",
      aiAnalysisError: "AI 分析失败。请重试。"
    }
  },
  VI: {
    subtitle: "Công cụ Tạo Bối cảnh & Tư vấn",
    admin: "Quản trị",
    reset: "Đặt lại",
    coreContext: "Bối cảnh Chính",
    landscape: "Kiến trúc & Hệ thống",
    landscapeArchitecture: "KIẾN TRÚC HỆ THỐNG",
    additionalDetails: "Chi tiết Bổ sung",
    additionalDetailsUpper: "CHI TIẾT BỔ SUNG",
    riseOpp: "Cơ hội RISE?",
    riseOppLabel: "Cơ hội RISE:",
    erpSystemLabel: "Hệ thống ERP:",
    adoptionLabel: "Áp dụng:",
    adoptionOpp: "Liên quan đến Adoption?",
    s4hana: "S/4HANA",
    sapEcc: "SAP ECC",
    nonSapErp: "ERP ngoài SAP",
    otherSap: "SAP khác",
    otherNonSap: "Ngoài SAP khác",
    contextAttachments: "Bối cảnh & Tệp đính kèm",
    attachFile: "Đính kèm Tệp",
    pastePlaceholder: "Dán chi tiết cụ thể...",
    consulting: "Tư vấn Chiến lược...",
    giveIdeas: "Gợi ý cho tôi",
    industry: "Ngành",
    process: "Lĩnh vực Quy trình",
    value: "Động lực Giá trị",
    capability: "Năng lực Giải pháp",
    dashboard: "Bảng điều khiển",
    exportCsv: "Xuất CSV",
    resetData: "Xóa Dữ liệu",
    noData: "Chưa có dữ liệu.",
    configHistory: "Lịch sử Cấu hình",
    savedConfig: "Cấu hình Đã lưu",
    restore: "Khôi phục",
    noVersions: "Chưa có phiên bản nào được lưu.",
    exportConfig: "Xuất Cấu hình",
    importConfig: "Nhập Cấu hình",
    knowledgeBase: "Cơ sở Tri thức",
    aiGuardrails: "Rào chắn AI & Nguồn",
    narrativeMethodology: "Phương pháp & Câu chuyện",
    dropdownLists: "Danh sách Tùy chọn",
    importKnowledge: "Nhập Tri thức",
    uploadPdf: "Tải PDF/Hình ảnh để đào tạo phương pháp.",
    selectFile: "Chọn Tệp",
    analyzing: "Đang phân tích...",
    valueMethodology: "Phương pháp Giá trị",
    marketingVoice: "Giọng điệu Marketing",
    guardrailsLabel: "Rào chắn & Ưu tiên",
    editList: "Sửa Danh sách",
    confirmReset: "Đặt lại Toàn bộ?",
    confirmResetMsg: "Thao tác này sẽ xóa tất cả lựa chọn. Dữ liệu chưa lưu sẽ bị mất.",
    confirmClearAnalytics: "Xóa Dữ liệu Sử dụng?",
    confirmClearAnalyticsMsg: "Thao tác này sẽ xóa toàn bộ lịch sử phân tích. Không thể hoàn tác.",
    accessGranted: "Đã Cấp Quyền",
    incorrectPass: "Sai Mật khẩu",
    configSaved: "Đã Lưu Cấu hình",
    helpCenter: "Trung tâm Trợ giúp",
    helpStart: "Bắt đầu",
    helpAdvanced: "Chức năng Nâng cao",
    helpVisual: "Bản đồ Trực quan",
    helpAdmin: "Quản trị & Cấu hình",
    noAdditionalContext: "Không có bối cảnh bổ sung.",
    notSpecified: "Chưa xác định",
    none: "Không có",
    noContextSelected: "Chưa Chọn Bối cảnh",
    selectContextPrompt: "Chọn ngành, quy trình và động lực giá trị để xây dựng bản đồ bối cảnh",
    readyToCoach: "Sẵn sàng Tư vấn",
    configureInputsPrompt: "Cấu hình đầu vào bên trái & nhấn \"Gợi ý cho tôi\"",
    coachThinking: "Đang suy nghĩ...",
    coachThinkingDesc: "Đang xây dựng chiến lược & luận điểm",
    briefNotGenerated: "Chưa Tạo Báo cáo",
    generateBriefNow: "Tạo Báo cáo Ngay",
    draftingDocument: "Đang Soạn Tài liệu...",
    draftingDesc: "Chuyển đổi ghi chú tư vấn thành báo cáo chính thức",
    emptyCoachingTitle: "Khám phá Tư vấn Chiến lược",
    emptyCoachingDesc: "Công cụ AI phân tích bối cảnh và đưa ra tư vấn chiến lược về giao dịch, thông điệp giá trị và định vị cạnh tranh.",
    quickStart: "Bắt đầu Nhanh:",
    quickStartManuf: "Sản xuất + Mua hàng đến Thanh toán",
    quickStartRetail: "Bán lẻ + Đặt hàng đến Thu tiền",
    quickStartFinance: "Ngân hàng + Ghi nhận đến Báo cáo",
    clearHistory: "Xóa Lịch sử",
    tabs: {
      coaching: "Ý tưởng",
      chat: "Trao đổi với Tư vấn",
      brief: "Báo cáo Chính thức",
      visual: "Bản đồ Trực quan",
      dealScore: "Đánh giá Giao dịch"
    },
    actions: {
      competitor: "Phân tích Đối thủ",
      draftBrief: "Soạn Báo cáo",
      email: "Email",
      objections: "Xử lý Phản đối",
      video: "Video 30 giây",
      agenda: "Chương trình",
      copy: "Sao chép Nội dung",
      increaseValue: "Tăng Giá trị!",
      stakeholders: "Bản đồ Bên liên quan",
      successStory: "Câu chuyện Thành công",
      signavio: "Tạo BPMN (Signavio)",
      leanix: "Mô hình Meta (LeanIX)",
      discovery: "Khám phá Thông minh",
      swot: "Phân tích SWOT",
      insights: "Phân tích Chiến lược"
    },
    meddic: {
      title: "Đánh giá Giao dịch MEDDIC",
      subtitle: "Khung bán hàng doanh nghiệp để đánh giá cơ hội",
      metrics: "Chỉ số",
      metricsDesc: "Kết quả kinh doanh đo lường được (ROI, KPI, mục tiêu tiết kiệm)",
      economicBuyer: "Người Quyết định Ngân sách",
      economicBuyerDesc: "Người có thẩm quyền ngân sách",
      decisionCriteria: "Tiêu chí Quyết định",
      decisionCriteriaDesc: "Tiêu chí kỹ thuật, kinh doanh và chính trị",
      decisionProcess: "Quy trình Quyết định",
      decisionProcessDesc: "Các bước, lịch trình, chuỗi phê duyệt",
      identifyPain: "Xác định Nỗi đau",
      identifyPainDesc: "Vấn đề kinh doanh quan trọng thúc đẩy sáng kiến",
      champion: "Người Ủng hộ",
      championDesc: "Người ủng hộ nội bộ bán hàng thay bạn",
      analyzeAI: "Phân tích bằng AI",
      analyzing: "Đang phân tích...",
      ruleBasedScore: "Điểm Quy tắc",
      aiAssessment: "Đánh giá AI",
      signals: "Thông tin Đã biết",
      aiEvidence: "Bằng chứng AI",
      missing: "Thông tin Còn thiếu",
      questionToAsk: "Câu hỏi Cần đặt",
      questionsToAsk: "Câu hỏi để Củng cố",
      noSignals: "Chưa có bằng chứng",
      scoreWeak: "Yếu",
      scoreModerate: "Trung bình",
      scoreStrong: "Mạnh",
      overallQualification: "Đánh giá Tổng thể",
      strongDimensions: "Mạnh",
      moderateDimensions: "Trung bình",
      weakDimensions: "Yếu",
      aiAnalysisError: "Phân tích AI thất bại. Vui lòng thử lại."
    }
  }
};
